// import { BsGithub, BsPlayCircle, BsLink45Deg, BsCodeSlash } from "react-icons/bs";
// import ReadingProgressBar from '../components/ui/ReadingProgressBar';
// import ScrollReveal from '../components/ui/ScrollReveal';
// import useDocumentTitle from '../hooks/useDocumentTitle';
// import './Experience.css';

// const Experience = () => {
//   useDocumentTitle('Projects');
//   const projects = [
//     {
//       title: 'Deep Learning NLP Challenge',
//       year: '2024',
//       // Mapped to 'summary' in render
//       description: 'Developed an advanced AI-powered learning assistant that transforms educational content into interactive study tools. Utilizing a multi-agent architecture powered by CrewAI and LangChain, the system ingests various formats (PDFs, YouTube videos, web resources) to provide personalized summaries, Q&A, and generated quizzes. The project features a voice-enabled interface using OpenAI Whisper and maintains long-term conversation context via a Qdrant vector database.',
//       // Mapped to 'technologies' in render
//       tags: ['Python', 'LangChain', 'CrewAI', 'Qdrant (Vector DB)', 'Groq API', 'OpenAI Whisper', 'React', 'FastAPI'],
//       githubUrl: 'https://github.com/egealkan/ai-projects/tree/main/NLP_Challenge',
//       pdfUrl: '/documents/AI Chatbot Development.pdf', 
//       videoUrl: 'https://youtu.be/M9aw8EZfyfc', 
//       learnings: 'Implemented the orchestration of multi-agent systems using CrewAI and learned how to manage long-term conversation context efficiently using vector databases (Qdrant) and RAG pipelines. I discovered that the hardest part of RAG isn\'t retrieval, but the "lost in the middle" phenomenon where agents ignore context. I learned to solve this by implementing strict context-window management and re-ranking, moving beyond simple vector similarity to semantic relevance.',
//       // Mapped to 'keyFeatures' logic in render
//       steps: [
//         {
//           title: 'Multi-Agent Orchestration',
//           description: 'Designed a robust agentic workflow using CrewAI, coordinating specialized agents (Content, QA, Research) to autonomously process materials and generate structured outputs.'
//         },
//         {
//           title: 'RAG & Vector Search',
//           description: 'Implemented a Retrieval-Augmented Generation (RAG) pipeline with Qdrant and LangChain to efficiently store and retrieve high-dimensional embeddings from course materials.'
//         },
//         {
//           title: 'Voice & Multimodal Interface',
//           description: 'Integrated OpenAI Whisper for accurate speech-to-text and Google gTTS for text-to-speech, creating a seamless hands-free conversational learning experience.'
//         },
//         {
//           title: 'Dynamic Study Tools',
//           description: 'Built a React-integrated frontend to render interactive quizzes and cheat sheets generated by the AI, resolving state management limitations found in Streamlit.'
//         }
//       ]
//     },
//     {
//       title: 'Neural Networks from Scratch',
//       year: '2025',
//       description: 'A dedicated research project focused on mastering the mathematical foundations of deep learning by building a neural network library entirely from scratch. By not using high-level frameworks like PyTorch or TensorFlow, I implemented core components using only Python and NumPy. This "first-principles" approach involved manually coding forward and backward propagation algorithms, activation functions, and optimizers to gain a granular understanding of how neural networks learn and converge on non-linear datasets.',
//       tags: ['Python', 'NumPy', 'Mathematics', 'Deep Learning', 'Backpropagation', 'Optimization'],
//       githubUrl: 'https://github.com/egealkan/AI-Projects/tree/main/AI_Practice_and_Math',
//       learnings: 'Gained a deep understanding of the calculus behind backpropagation and gradient descent by implementing them without auto-differentiation libraries, reinforcing the mathematical foundations of AI. Writing backpropagation by hand taught me that "vanishing gradients" isn\'t just a textbook concept but a tangible bug caused by poor weight initialization. I learned to manually derive chain rule derivatives, which completely changed how I debug convergence issues in modern frameworks like PyTorch.',
//       steps: [
//         {
//           title: 'Core Architecture',
//           description: 'Implemented fully-connected (dense) layers using matrix operations in NumPy, handling weight initialization and bias implementation manually to structure the network.'
//         },
//         {
//           title: 'Activation Functions',
//           description: 'Coded non-linear activation functions from scratch, including ReLU (for hidden layers) and Softmax (for output probability distribution), ensuring numerical stability during calculations.'
//         },
//         {
//           title: 'Backpropagation Engine',
//           description: 'Engineered the complete backward pass logic to calculate partial derivatives and gradients for all components, enabling the network to learn via the chain rule.'
//         },
//         {
//           title: 'Loss & Optimization',
//           description: 'Developed a custom Categorical Cross-Entropy loss function and a Stochastic Gradient Descent (SGD) optimizer to measure error and update model parameters iteratively.'
//         }
//       ]
//     },
//     {
//       title: 'AI-Powered Particle Accelerator Simulation',
//       year: '2025 - Present',
//       description: 'An ambitious ongoing personal research project aimed at building a complete "Digital Physics Laboratory" to simulate high-energy particle collisions similar to those at the Large Hadron Collider (LHC). Unlike standard data analysis projects, this system simulates its own raw physics data using industry-standard tools like PYTHIA8 and ROOT. I am currently developing a multi-stage AI pipeline designed to "rediscover" known particles (like the Z and Higgs bosons) and detect potential "new physics" via unsupervised anomaly detection. The project is being architected as a full-stack application with a FastAPI backend and an immersive 3D frontend, working towards creating an autonomous scientific assistant.',
//       tags: ['Python', 'PyTorch', 'PYTHIA8', 'ROOT (CERN)', 'FastAPI', 'Three.js', 'Anomaly Detection', 'SciPy'],
//       githubUrl: 'https://github.com/egealkan/particle_accelerator',
//       learnings: 'I learned that in high-energy physics, "accuracy" is less important than "explainability." Implementing unsupervised detection taught me to validate model outputs against theoretical Monte Carlo baselines, bridging the gap between black-box AI and rigorous scientific standards. I Learned to bridge the gap between theoretical physics simulations (Monte Carlo) and modern AI, specifically applying unsupervised anomaly detection to identify statistical outliers in high-energy datasets.',
//       steps: [
//         {
//           title: 'High-Energy Physics Engine',
//           description: 'Engineering a robust simulation pipeline using the PYTHIA8 Monte Carlo generator to produce realistic collision events. Work is underway to integrate CERN\'s ROOT framework for high-performance data processing, enabling the extraction of complex kinematic properties.'
//         },
//         {
//           title: 'AI Discovery Pipeline',
//           description: 'Building and training specialized neural networks to act as a "Digital Physicist." This involves developing binary classifiers for identifying specific decay signatures and autoencoder-based anomaly detection systems to flag statistically significant outliers.'
//         },
//         {
//           title: 'Interactive 3D Laboratory',
//           description: 'Developing a real-time visualization interface using React and Three.js. The goal is to render particle decay chains in a 3D interactive space, allowing users to visually inspect momentum vectors and energy deposits.'
//         },
//         {
//           title: 'Automated Research Reporting',
//           description: 'Implementing an NLP-driven analysis engine to process statistical output. The system is being designed to automatically generate human-readable reports, calculate statistical significance, and visualize invariant mass distributions to automate scientific discovery.'
//         }
//       ]
//     },
//     {
//       title: 'Autonomous Driving CV Challenge',
//       year: '2024',
//       description: 'Developed a deep learning-based autonomous driving system for the Trackmania racing game using computer vision. The goal was to navigate a vehicle in real-time using only visual input. I engineered a custom data pipeline to capture gameplay and trained various Convolutional Neural Network (CNN) architectures, including ResNet-34, ResNet-50, and CNN-LSTM hybrids, to predict steering and throttle commands. The project utilized advanced training techniques like one-cycle learning rates and mixed precision to achieve high accuracy on validation datasets.',
//       tags: ['Python', 'FastAI', 'PyTorch', 'OpenCV', 'ResNet CNN', 'LSTM', 'YOLOv8', 'Data Augmentation'],
//       githubUrl: 'https://github.com/egealkan/ai-projects/tree/main/Computer_Vision_Challenge',
//       pdfUrl: '/documents/Autonomous-Driving-Project-Presentation.pdf',
//       learnings: 'Understood the critical importance of data balancing and augmentation in imitation learning, and learned optimization techniques like Mixed Precision training to accelerate model convergence. I realized that imitation learning is fragile; the model initially memorized the track background rather than road features. This forced me to implement aggressive augmentation strategies (shadows, flips), teaching me that a robust dataset is far more critical than a complex architecture for generalization.',
//       steps: [
//         {
//           title: 'Data Collection & Pipeline',
//           description: 'Created a custom Python script using ImageGrab and Pynput to capture synchronized gameplay frames and directional key inputs, building a dataset that was balanced and augmented to handle the game\'s high-speed dynamics.'
//         },
//         {
//           title: 'Model Architecture Research',
//           description: 'Iteratively implemented and evaluated multiple deep learning models, comparing ResNet-18, ResNet-34, and ResNet-50 architectures, and exploring CNN-LSTM hybrids to better capture temporal driving dependencies.'
//         },
//         {
//           title: 'Optimization & Training',
//           description: 'Utilized FastAI to implement advanced training strategies such as the One-Cycle Policy, Mixed Precision Training, and Dropout Regularization, significantly improving model convergence and inference speed.'
//         },
//         {
//           title: 'Real-Time Autonomous Control',
//           description: 'Deployed the trained model into a live "capture-and-drive" loop that processes game frames in real-time and maps model predictions to virtual keyboard outputs to drive the car autonomously.'
//         }
//       ]
//     },
//     {
//       title: 'Frank de Bank - BenchMark',
//       year: '2024',
//       description: 'An innovative AI-powered "talking bench" installation developed for Rurant to gather community feedback on rural planning. As the AI Lead, I architected the conversational core using Google Gemini and FastAPI. The system engages citizens in natural, open-ended dialogues, collecting their opinions while analyzing emotional sentiment in real-time. This feedback is then processed to provide city planners with actionable insights into public sentiment regarding specific locations.',
//       tags: ['Python', 'FastAPI', 'Google Gemini AI', 'Google Cloud STT/TTS', 'Emotion Analysis', 'Docker', 'React', 'Raspberry Pi'],
//       githubUrl: 'https://github.com/egealkan/AI-Projects/tree/main/Project_4.0_Talking_Bench',
//       learnings: 'Learned to architect a hybrid IoT-Cloud solution, handling the challenges of real-time audio processing and latency management when integrating hardware (Raspberry Pi) with LLM APIs. Integrating a Raspberry Pi with LLMs taught me that network latency is the biggest bottleneck in voice interfaces. I learned to optimize the audio buffer streams and implement local processing where possible to shave off critical milliseconds, creating a fluid conversation loop rather than just a request-response cycle.',
//       steps: [
//         {
//           title: 'Conversational AI Engine',
//           description: 'Integrated Google Gemini (LLM) to power context-aware, open-ended conversations, enabling the bench to ask relevant follow-up questions and maintain natural dialogue flow.'
//         },
//         {
//           title: 'Voice Processing Pipeline',
//           description: 'Developed a robust speech-to-speech system using Google Cloud STT and TTS services, capable of capturing voice input in outdoor environments and responding with natural-sounding speech.'
//         },
//         {
//           title: 'Emotion & Sentiment Analysis',
//           description: 'Implemented a dedicated emotion analyzer module to detect user sentiment during interactions, adding a layer of emotional intelligence to the gathered feedback data.'
//         },
//         {
//           title: 'Scalable Backend Architecture',
//           description: 'Built a containerized REST API using FastAPI and Docker to manage conversation sessions, audio processing, and analytics logging for the frontend interface.'
//         }
//       ]
//     },
//     {
//       title: 'Training Session Management System',
//       year: '2025',
//       description: 'A comprehensive web application built with PHP and Laravel to digitize the administration of student training sessions. This semester-long group project created a centralized platform for students to form teams, select topics, and communicate with clients, while empowering teachers and coordinators with granular administrative control. The system features role-based access for Students, Coaches, and Coordinators to streamline the entire academic workflow.\n\nDemo Credentials:\nStudent: test1@example.com (pw: password)\nCoach: test@example.com (pw: password\nCoordinator: test2@example.com (pw: password)',
//       tags: ['PHP', 'Laravel', 'Blade', 'MySQL', 'Tailwind CSS', 'Group Project'],
//       links: {
//         demo: "https://skill2.bragi.be"
//       },
//       learnings: 'Experienced the complexity of designing secure Role-Based Access Control (RBAC) systems and managing full-stack MVC architecture within a collaborative agile team environment. I learned that tight coupling between UI and logic kills scalability. By refactoring our monolithic controllers into a service-based architecture mid-project, I understood the tangible value of Dependency Injection not just for testing, but for allowing multiple developers to work on the same feature without conflicts.',
//       steps: [
//         {
//           title: 'Role-Based Access Control',
//           description: 'Architected a secure permission system that serves distinct interfaces and functionalities to three different user roles (Student, Coach, Coordinator) within the same application.'
//         },
//         {
//           title: 'Workflow Automation',
//           description: 'Digitized the manual process of topic selection and team formation, allowing students to browse opportunities and manage their groups while automating status updates and notifications.'
//         },
//         {
//           title: 'Admin Management Suite',
//           description: 'Created extensive administrative features for coordinators to manage the lifecycle of the training program, including user management, client oversight, and global system configuration.'
//         },
//         {
//           title: 'Laravel MVC Implementation',
//           description: 'Developed the application using the Model-View-Controller architecture, utilizing Laravel\'s Eloquent ORM for database interactions and Blade templating for a dynamic and responsive frontend.'
//         }
//       ]
//     },
//   ];

//   return (
//     <div className="experience-page">
//       <ReadingProgressBar />
//       <div className="container">
//         <h1 className="page-title">Project Showcases</h1>
//         <p className="page-subtitle">
//           A collection of my technical projects, ranging from AI & Machine Learning to Full Stack Web Development.
//         </p>
        
//         <div className="projects-grid">
//           {projects.map((project, index) => (
//             <ScrollReveal key={index}>
//               <article className="project-card">
//               <div className="project-header">
//                 <div className="project-icon">
//                   <BsCodeSlash />
//                 </div>
//                 <div className="project-title-wrapper">
//                   {/* Handle optional category */}
//                   {project.category ? (
//                     <span className="project-category">{project.category}</span>
//                   ) : (
//                     <span className="project-category">Featured Project</span>
//                   )}
//                   <h2 className="project-title">{project.title}</h2>
//                 </div>
//               </div>

//               <div className="project-content">
//                 {/* Handle both description and summary fields */}
//                 <p className="project-summary">{project.description || project.summary}</p>
                
//                 <div className="project-details-grid">
//                   <div className="features-section">
//                     <h3 className="section-heading">Key Features</h3>
//                     <ul className="feature-list">
//                       {/* Handle structured steps from NLP project */}
//                       {project.steps ? (
//                         project.steps.map((step, i) => (
//                           <li key={i} className="feature-item">
//                             <strong>{step.title}:</strong> {step.description}
//                           </li>
//                         ))
//                       ) : (
//                         /* Handle standard string array keyFeatures */
//                         project.keyFeatures?.map((feature, i) => (
//                           <li key={i} className="feature-item">{feature}</li>
//                         ))
//                       )}
//                     </ul>
//                   </div>

//                   <div className="learnings-section">
//                     <h3 className="section-heading">What I Learned</h3>
//                     <p className="project-learning-text">
//                       {project.learnings}
//                     </p>
//                   </div>
                  
//                   <div className="tech-section">
//                     <h3 className="section-heading">Technologies</h3>
//                     <div className="tech-tags">
//                       {/* Handle both tags and technologies fields */}
//                       {(project.tags || project.technologies)?.map((tech, i) => (
//                         <span key={i} className="tech-tag">{tech}</span>
//                       ))}
//                     </div>
//                   </div>
//                 </div>

//                 {/* PDF Presentation Viewer (Only for NLP Project) */}
//                 {project.pdfUrl && (
//                   <div className="pdf-container" style={{ marginTop: '2rem', marginBottom: '1rem' }}>
//                     <h4 style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '0.5rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Project Presentation</h4>
//                     <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', fontStyle: 'italic', opacity: 0.7 }}>
//                         (Preview may take a moment to load. If it doesn't load, please refresh the page.)
//                     </span>
//                     <div style={{ position: 'relative', height: '0', paddingBottom: '56.25%', border: '1px solid var(--border-color)', borderRadius: '8px', overflow: 'hidden', background: 'var(--bg-secondary)' }}>
//                       <iframe 
//                         // src={`${project.pdfUrl}#toolbar=0&navpanes=0&scrollbar=1&view=FitH`}
//                         src={`https://docs.google.com/viewer?url=${encodeURIComponent('https://egealkan.github.io' + project.pdfUrl)}&embedded=true`}
//                         title={`${project.title} Presentation`}
//                         width="100%" 
//                         height="100%" 
//                         style={{ position: 'absolute', top: 0, left: 0 }}
//                       >
//                       </iframe>
//                     </div>
//                   </div>
//                 )}

//                 {/* Media & Links Section */}
//                 <div className="project-footer">
//                   <div className="project-links">
//                     {/* Handle GitHub Link */}
//                     {(project.githubUrl || project.links?.github) && (
//                       <a href={project.githubUrl || project.links.github} target="_blank" rel="noopener noreferrer" className="link-btn github">
//                         <BsGithub /> Source Code
//                       </a>
//                     )}
//                     {/* Handle Demo Link */}
//                     {project.links?.demo && (
//                       <a href={project.links.demo} target="_blank" rel="noopener noreferrer" className="link-btn demo">
//                         <BsLink45Deg /> Live Demo
//                       </a>
//                     )}
//                   </div>

//                   {/* Video Handling: Embed if videoUrl exists, otherwise use placeholder */}
//                   {project.videoUrl ? (
//                     <div className="video-showcase" style={{ width: '100%', marginTop: '1rem' }}>
//                       <div className="video-container" style={{ position: 'relative', paddingBottom: '56.25%', height: 0, borderRadius: '8px', overflow: 'hidden' }}>
//                         <iframe
//                           src={`https://www.youtube.com/embed/${project.videoUrl.split('/').pop().replace('watch?v=', '')}`}
//                           title={`${project.title} Demo`}
//                           frameBorder="0"
//                           allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
//                           allowFullScreen
//                           style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%' }}
//                         ></iframe>
//                       </div>
//                     </div>
//                   ) : (
//                     project.links?.video && (
//                       <div className="video-preview">
//                         <div className="video-placeholder">
//                           <BsPlayCircle className="play-icon" />
//                           <span>Watch Demo</span>
//                         </div>
//                       </div>
//                     )
//                   )}
//                 </div>
//               </div>
//             </article>
//             </ScrollReveal>
//           ))}
//         </div>
//       </div>
//     </div>
//   );
// };

// export default Experience;










import { useState, useEffect } from 'react';
import { 
  BsGithub, 
  BsPlayCircle, 
  BsLink45Deg, 
  BsCodeSlash, 
  BsX, 
  BsArrowRight,
  BsRobot,       // For NLP/AI
  BsCpu,         // For Neural Networks/Math
  BsActivity,    // For Physics/Simulation
  BsCarFront,    // For Autonomous Driving
  BsChatQuote,   // For Talking Bench
  BsLaptop       // For Web/Management System
} from "react-icons/bs";
import ReadingProgressBar from '../components/ui/ReadingProgressBar';
import ScrollReveal from '../components/ui/ScrollReveal';
import useDocumentTitle from '../hooks/useDocumentTitle';
import './Experience.css';

const Experience = () => {
  useDocumentTitle('Projects');
  const [selectedProject, setSelectedProject] = useState(null);

  // Prevent background scrolling when modal is open
  useEffect(() => {
    if (selectedProject) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = 'unset';
    }
    return () => { document.body.style.overflow = 'unset'; };
  }, [selectedProject]);

  const projects = [
    {
      title: 'Deep Learning NLP Challenge',
      year: '2024',
      icon: <BsRobot />,
      description: 'Developed an advanced AI-powered learning assistant that transforms educational content into interactive study tools. Utilizing a multi-agent architecture powered by CrewAI and LangChain, the system ingests various formats (PDFs, YouTube videos, web resources) to provide personalized summaries, Q&A, and generated quizzes. The project features a voice-enabled interface using OpenAI Whisper and maintains long-term conversation context via a Qdrant vector database.',
      tags: ['Python', 'LangChain', 'CrewAI', 'Qdrant (Vector DB)', 'Groq API', 'OpenAI Whisper', 'React', 'FastAPI'],
      githubUrl: 'https://github.com/egealkan/ai-projects/tree/main/NLP_Challenge',
      pdfUrl: '/documents/AI Chatbot Development.pdf', 
      videoUrl: 'https://youtu.be/M9aw8EZfyfc', 
      learnings: 'Implemented the orchestration of multi-agent systems using CrewAI and learned how to manage long-term conversation context efficiently using vector databases (Qdrant) and RAG pipelines. I discovered that the hardest part of RAG isn\'t retrieval, but the "lost in the middle" phenomenon where agents ignore context. I learned to solve this by implementing strict context-window management and re-ranking, moving beyond simple vector similarity to semantic relevance.',
      steps: [
        {
          title: 'Multi-Agent Orchestration',
          description: 'Designed a robust agentic workflow using CrewAI, coordinating specialized agents (Content, QA, Research) to autonomously process materials and generate structured outputs.'
        },
        {
          title: 'RAG & Vector Search',
          description: 'Implemented a Retrieval-Augmented Generation (RAG) pipeline with Qdrant and LangChain to efficiently store and retrieve high-dimensional embeddings from course materials.'
        },
        {
          title: 'Voice & Multimodal Interface',
          description: 'Integrated OpenAI Whisper for accurate speech-to-text and Google gTTS for text-to-speech, creating a seamless hands-free conversational learning experience.'
        },
        {
          title: 'Dynamic Study Tools',
          description: 'Built a React-integrated frontend to render interactive quizzes and cheat sheets generated by the AI, resolving state management limitations found in Streamlit.'
        }
      ]
    },
    {
      title: 'Neural Networks from Scratch',
      year: '2025',
      icon: <BsCpu />,
      description: 'A dedicated research project focused on mastering the mathematical foundations of deep learning by building a neural network library entirely from scratch. By not using high-level frameworks like PyTorch or TensorFlow, I implemented core components using only Python and NumPy. This "first-principles" approach involved manually coding forward and backward propagation algorithms, activation functions, and optimizers to gain a granular understanding of how neural networks learn and converge on non-linear datasets.',
      tags: ['Python', 'NumPy', 'Mathematics', 'Deep Learning', 'Backpropagation', 'Optimization'],
      githubUrl: 'https://github.com/egealkan/AI-Projects/tree/main/AI_Practice_and_Math',
      learnings: 'Gained a deep understanding of the calculus behind backpropagation and gradient descent by implementing them without auto-differentiation libraries, reinforcing the mathematical foundations of AI. Writing backpropagation by hand taught me that "vanishing gradients" isn\'t just a textbook concept but a tangible bug caused by poor weight initialization. I learned to manually derive chain rule derivatives, which completely changed how I debug convergence issues in modern frameworks like PyTorch.',
      steps: [
        {
          title: 'Core Architecture',
          description: 'Implemented fully-connected (dense) layers using matrix operations in NumPy, handling weight initialization and bias implementation manually to structure the network.'
        },
        {
          title: 'Activation Functions',
          description: 'Coded non-linear activation functions from scratch, including ReLU (for hidden layers) and Softmax (for output probability distribution), ensuring numerical stability during calculations.'
        },
        {
          title: 'Backpropagation Engine',
          description: 'Engineered the complete backward pass logic to calculate partial derivatives and gradients for all components, enabling the network to learn via the chain rule.'
        },
        {
          title: 'Loss & Optimization',
          description: 'Developed a custom Categorical Cross-Entropy loss function and a Stochastic Gradient Descent (SGD) optimizer to measure error and update model parameters iteratively.'
        }
      ]
    },
    {
      title: 'AI-Powered Particle Accelerator Simulation',
      year: '2025 - Present',
      icon: <BsActivity />,
      description: 'An ambitious ongoing personal research project aimed at building a complete "Digital Physics Laboratory" to simulate high-energy particle collisions similar to those at the Large Hadron Collider (LHC). Unlike standard data analysis projects, this system simulates its own raw physics data using industry-standard tools like PYTHIA8 and ROOT. I am currently developing a multi-stage AI pipeline designed to "rediscover" known particles (like the Z and Higgs bosons) and detect potential "new physics" via unsupervised anomaly detection. The project is being architected as a full-stack application with a FastAPI backend and an immersive 3D frontend, working towards creating an autonomous scientific assistant.',
      tags: ['Python', 'PyTorch', 'PYTHIA8', 'ROOT (CERN)', 'FastAPI', 'Three.js', 'Anomaly Detection', 'SciPy'],
      githubUrl: 'https://github.com/egealkan/particle_accelerator',
      learnings: 'I learned that in high-energy physics, "accuracy" is less important than "explainability." Implementing unsupervised detection taught me to validate model outputs against theoretical Monte Carlo baselines, bridging the gap between black-box AI and rigorous scientific standards. I Learned to bridge the gap between theoretical physics simulations (Monte Carlo) and modern AI, specifically applying unsupervised anomaly detection to identify statistical outliers in high-energy datasets.',
      steps: [
        {
          title: 'High-Energy Physics Engine',
          description: 'Engineering a robust simulation pipeline using the PYTHIA8 Monte Carlo generator to produce realistic collision events. Work is underway to integrate CERN\'s ROOT framework for high-performance data processing, enabling the extraction of complex kinematic properties.'
        },
        {
          title: 'AI Discovery Pipeline',
          description: 'Building and training specialized neural networks to act as a "Digital Physicist." This involves developing binary classifiers for identifying specific decay signatures and autoencoder-based anomaly detection systems to flag statistically significant outliers.'
        },
        {
          title: 'Interactive 3D Laboratory',
          description: 'Developing a real-time visualization interface using React and Three.js. The goal is to render particle decay chains in a 3D interactive space, allowing users to visually inspect momentum vectors and energy deposits.'
        },
        {
          title: 'Automated Research Reporting',
          description: 'Implementing an NLP-driven analysis engine to process statistical output. The system is being designed to automatically generate human-readable reports, calculate statistical significance, and visualize invariant mass distributions to automate scientific discovery.'
        }
      ]
    },
    {
      title: 'Autonomous Driving CV Challenge',
      year: '2024',
      icon: <BsCarFront />,
      description: 'Developed a deep learning-based autonomous driving system for the Trackmania racing game using computer vision. The goal was to navigate a vehicle in real-time using only visual input. I engineered a custom data pipeline to capture gameplay and trained various Convolutional Neural Network (CNN) architectures, including ResNet-34, ResNet-50, and CNN-LSTM hybrids, to predict steering and throttle commands. The project utilized advanced training techniques like one-cycle learning rates and mixed precision to achieve high accuracy on validation datasets.',
      tags: ['Python', 'FastAI', 'PyTorch', 'OpenCV', 'ResNet CNN', 'LSTM', 'YOLOv8', 'Data Augmentation'],
      githubUrl: 'https://github.com/egealkan/ai-projects/tree/main/Computer_Vision_Challenge',
      pdfUrl: '/documents/Autonomous-Driving-Project-Presentation.pdf',
      learnings: 'Understood the critical importance of data balancing and augmentation in imitation learning, and learned optimization techniques like Mixed Precision training to accelerate model convergence. I realized that imitation learning is fragile; the model initially memorized the track background rather than road features. This forced me to implement aggressive augmentation strategies (shadows, flips), teaching me that a robust dataset is far more critical than a complex architecture for generalization.',
      steps: [
        {
          title: 'Data Collection & Pipeline',
          description: 'Created a custom Python script using ImageGrab and Pynput to capture synchronized gameplay frames and directional key inputs, building a dataset that was balanced and augmented to handle the game\'s high-speed dynamics.'
        },
        {
          title: 'Model Architecture Research',
          description: 'Iteratively implemented and evaluated multiple deep learning models, comparing ResNet-18, ResNet-34, and ResNet-50 architectures, and exploring CNN-LSTM hybrids to better capture temporal driving dependencies.'
        },
        {
          title: 'Optimization & Training',
          description: 'Utilized FastAI to implement advanced training strategies such as the One-Cycle Policy, Mixed Precision Training, and Dropout Regularization, significantly improving model convergence and inference speed.'
        },
        {
          title: 'Real-Time Autonomous Control',
          description: 'Deployed the trained model into a live "capture-and-drive" loop that processes game frames in real-time and maps model predictions to virtual keyboard outputs to drive the car autonomously.'
        }
      ]
    },
    {
      title: 'Frank de Bank - BenchMark',
      year: '2024',
      icon: <BsChatQuote />,
      description: 'An innovative AI-powered "talking bench" installation developed for Rurant to gather community feedback on rural planning. As the AI Lead, I architected the conversational core using Google Gemini and FastAPI. The system engages citizens in natural, open-ended dialogues, collecting their opinions while analyzing emotional sentiment in real-time. This feedback is then processed to provide city planners with actionable insights into public sentiment regarding specific locations.',
      tags: ['Python', 'FastAPI', 'Google Gemini AI', 'Google Cloud STT/TTS', 'Emotion Analysis', 'Docker', 'React', 'Raspberry Pi'],
      githubUrl: 'https://github.com/egealkan/AI-Projects/tree/main/Project_4.0_Talking_Bench',
      learnings: 'Learned to architect a hybrid IoT-Cloud solution, handling the challenges of real-time audio processing and latency management when integrating hardware (Raspberry Pi) with LLM APIs. Integrating a Raspberry Pi with LLMs taught me that network latency is the biggest bottleneck in voice interfaces. I learned to optimize the audio buffer streams and implement local processing where possible to shave off critical milliseconds, creating a fluid conversation loop rather than just a request-response cycle.',
      steps: [
        {
          title: 'Conversational AI Engine',
          description: 'Integrated Google Gemini (LLM) to power context-aware, open-ended conversations, enabling the bench to ask relevant follow-up questions and maintain natural dialogue flow.'
        },
        {
          title: 'Voice Processing Pipeline',
          description: 'Developed a robust speech-to-speech system using Google Cloud STT and TTS services, capable of capturing voice input in outdoor environments and responding with natural-sounding speech.'
        },
        {
          title: 'Emotion & Sentiment Analysis',
          description: 'Implemented a dedicated emotion analyzer module to detect user sentiment during interactions, adding a layer of emotional intelligence to the gathered feedback data.'
        },
        {
          title: 'Scalable Backend Architecture',
          description: 'Built a containerized REST API using FastAPI and Docker to manage conversation sessions, audio processing, and analytics logging for the frontend interface.'
        }
      ]
    },
    {
      title: 'Training Session Management System',
      year: '2025',
      icon: <BsLaptop />,
      description: 'A comprehensive web application built with PHP and Laravel to digitize the administration of student training sessions. This semester-long group project created a centralized platform for students to form teams, select topics, and communicate with clients, while empowering teachers and coordinators with granular administrative control. The system features role-based access for Students, Coaches, and Coordinators to streamline the entire academic workflow.\n\nDemo Credentials:\nStudent: test1@example.com (pw: password)\nCoach: test@example.com (pw: password\nCoordinator: test2@example.com (pw: password)',
      tags: ['PHP', 'Laravel', 'Blade', 'MySQL', 'Tailwind CSS', 'Group Project'],
      links: {
        demo: "https://skill2.bragi.be"
      },
      learnings: 'Experienced the complexity of designing secure Role-Based Access Control (RBAC) systems and managing full-stack MVC architecture within a collaborative agile team environment. I learned that tight coupling between UI and logic kills scalability. By refactoring our monolithic controllers into a service-based architecture mid-project, I understood the tangible value of Dependency Injection not just for testing, but for allowing multiple developers to work on the same feature without conflicts.',
      steps: [
        {
          title: 'Role-Based Access Control',
          description: 'Architected a secure permission system that serves distinct interfaces and functionalities to three different user roles (Student, Coach, Coordinator) within the same application.'
        },
        {
          title: 'Workflow Automation',
          description: 'Digitized the manual process of topic selection and team formation, allowing students to browse opportunities and manage their groups while automating status updates and notifications.'
        },
        {
          title: 'Admin Management Suite',
          description: 'Created extensive administrative features for coordinators to manage the lifecycle of the training program, including user management, client oversight, and global system configuration.'
        },
        {
          title: 'Laravel MVC Implementation',
          description: 'Developed the application using the Model-View-Controller architecture, utilizing Laravel\'s Eloquent ORM for database interactions and Blade templating for a dynamic and responsive frontend.'
        }
      ]
    },
  ];

  return (
    <div className="experience-page">
      <ReadingProgressBar />
      <div className="container">
        <h1 className="page-title">Project Showcases</h1>
        <p className="page-subtitle">
          A collection of my technical projects, ranging from AI & Machine Learning to Full Stack Web Development.
        </p>
        
        {/* Grid of Summary Cards */}
        <div className="projects-grid">
          {projects.map((project, index) => (
            <ScrollReveal key={index}>
              <div className="project-summary-card" onClick={() => setSelectedProject(project)}>
                <div className="summary-card-header">
                  <div className="summary-icon">
                    {/* Use the specific project icon here */}
                    {project.icon}
                  </div>
                  {project.category ? (
                    <span className="summary-category">{project.category}</span>
                  ) : (
                    <span className="summary-category">Featured Project</span>
                  )}
                </div>
                
                <h3 className="summary-title">{project.title}</h3>
                
                <p className="summary-text">
                  {project.description.length > 120 
                    ? project.description.substring(0, 120) + '...' 
                    : project.description}
                </p>

                <div className="summary-tags">
                  {(project.tags || project.technologies)?.slice(0, 3).map((tech, i) => (
                    <span key={i} className="summary-tag">{tech}</span>
                  ))}
                  {(project.tags || project.technologies)?.length > 3 && (
                    <span className="summary-tag-more">+{((project.tags || project.technologies)?.length) - 3}</span>
                  )}
                </div>

                <div className="summary-footer">
                   <button className="read-more-btn">
                     See Project <BsArrowRight />
                   </button>
                   {project.year && <span className="summary-year">{project.year}</span>}
                </div>
              </div>
            </ScrollReveal>
          ))}
        </div>
      </div>

      {/* Project Detail Modal */}
      {selectedProject && (
        <div className="modal-overlay" onClick={() => setSelectedProject(null)}>
          <div className="modal-container" onClick={(e) => e.stopPropagation()}>
            <button className="close-modal-btn" onClick={() => setSelectedProject(null)}>
              <BsX />
            </button>
            
            <div className="modal-content-scroll">
              {/* Original Project Card Structure Preserved Here */}
              <article className="project-card">
                <div className="project-header">
                  <div className="project-icon">
                    {/* Use the specific project icon here */}
                    {selectedProject.icon}
                  </div>
                  <div className="project-title-wrapper">
                    {selectedProject.category ? (
                      <span className="project-category">{selectedProject.category}</span>
                    ) : (
                      <span className="project-category">Featured Project</span>
                    )}
                    <h2 className="project-title">{selectedProject.title}</h2>
                  </div>
                </div>

                <div className="project-content">
                  <p className="project-summary">{selectedProject.description || selectedProject.summary}</p>
                  
                  <div className="project-details-grid">
                    <div className="features-section">
                      <h3 className="section-heading">Key Features</h3>
                      <ul className="feature-list">
                        {selectedProject.steps ? (
                          selectedProject.steps.map((step, i) => (
                            <li key={i} className="feature-item">
                              <strong>{step.title}:</strong> {step.description}
                            </li>
                          ))
                        ) : (
                          selectedProject.keyFeatures?.map((feature, i) => (
                            <li key={i} className="feature-item">{feature}</li>
                          ))
                        )}
                      </ul>
                    </div>

                    <div className="learnings-section">
                      <h3 className="section-heading">What I Learned</h3>
                      <p className="project-learning-text">
                        {selectedProject.learnings}
                      </p>
                    </div>
                    
                    <div className="tech-section">
                      <h3 className="section-heading">Technologies</h3>
                      <div className="tech-tags">
                        {(selectedProject.tags || selectedProject.technologies)?.map((tech, i) => (
                          <span key={i} className="tech-tag">{tech}</span>
                        ))}
                      </div>
                    </div>
                  </div>

                  {/* PDF Presentation Viewer */}
                  {selectedProject.pdfUrl && (
                    <div className="pdf-container" style={{ marginTop: '2rem', marginBottom: '1rem' }}>
                      <h4 style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '0.5rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Project Presentation</h4>
                      <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', fontStyle: 'italic', opacity: 0.7 }}>
                          (Preview may take a moment to load. If it doesn't load, please refresh the page.)
                      </span>
                      <div style={{ position: 'relative', height: '0', paddingBottom: '56.25%', border: '1px solid var(--border-color)', borderRadius: '8px', overflow: 'hidden', background: 'var(--bg-secondary)' }}>
                        <iframe 
                          src={`https://docs.google.com/viewer?url=${encodeURIComponent('https://egealkan.github.io' + selectedProject.pdfUrl)}&embedded=true`}
                          title={`${selectedProject.title} Presentation`}
                          width="100%" 
                          height="100%" 
                          style={{ position: 'absolute', top: 0, left: 0 }}
                        >
                        </iframe>
                      </div>
                    </div>
                  )}

                  {/* Media & Links Section */}
                  <div className="project-footer">
                    <div className="project-links">
                      {(selectedProject.githubUrl || selectedProject.links?.github) && (
                        <a href={selectedProject.githubUrl || selectedProject.links.github} target="_blank" rel="noopener noreferrer" className="link-btn github">
                          <BsGithub /> Source Code
                        </a>
                      )}
                      {selectedProject.links?.demo && (
                        <a href={selectedProject.links.demo} target="_blank" rel="noopener noreferrer" className="link-btn demo">
                          <BsLink45Deg /> Live Demo
                        </a>
                      )}
                    </div>

                    {selectedProject.videoUrl ? (
                      <div className="video-showcase" style={{ width: '100%', marginTop: '1rem' }}>
                        <div className="video-container" style={{ position: 'relative', paddingBottom: '56.25%', height: 0, borderRadius: '8px', overflow: 'hidden' }}>
                          <iframe
                            src={`https://www.youtube.com/embed/${selectedProject.videoUrl.split('/').pop().replace('watch?v=', '')}`}
                            title={`${selectedProject.title} Demo`}
                            frameBorder="0"
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                            allowFullScreen
                            style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%' }}
                          ></iframe>
                        </div>
                      </div>
                    ) : (
                      selectedProject.links?.video && (
                        <div className="video-preview">
                          <div className="video-placeholder">
                            <BsPlayCircle className="play-icon" />
                            <span>Watch Demo</span>
                          </div>
                        </div>
                      )
                    )}
                  </div>
                </div>
              </article>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Experience;